### ISSUE TITLE
Limit the degrees of freedom for non-active phases in MCMC to prevent them from diverging?

### ISSUE THREAD

**Issue by bocklund** [PhasesResearchLab/ESPEI#10]
Phases that do not have phase equilibria data should have their parameters fixed before the MCMC run.

A particular phase in an ESPEI run can have single phase DFT data and no phase equilibria. This means that the parameters that were calculated in the single phase fitting have no effect on the error function that is used in the MCMC run. 

When parameters have no effect on the error function, they diverge when used in emcee because the ensemble sampler scales them up to infinity in an attempt to force that parameter to affect the error function.

**Comment by bocklund** [comment]
After more thought, this is high priority. 

If we don't have any ZPF data for the composition of a phase, we should not fit that phase.

An example is that if there is no data for the solubility of a terminal solution, (e.g. terminal fcc phase) then any mixing parameters that may have been calculated by DFT should not be fit.

If there are estimates for this solubility example (or others) then they should be labeled as such and could be included.

**Comment by bocklund** [comment]
I'm not sure that it would be correct to essentially 'freeze in' the energetics of one phase, when another phase does have an equilibria with that phase, like in the liqudius composition + null solidus case.

**Comment by richardotis** [comment]
It's correct to the extent that the energetics of the frozen-in phase are correct. From a Bayesian perspective, the priors for those parameters are delta functions located at the frozen value. Like any choice of strong prior, it may distort the posterior distribution if chosen poorly.

**Comment by bocklund** [comment]
In OOB discussions, we are going to take an approach that considers single phase data in the MCMC likelihood to anchor energies off the convex hull to their DFT values.

**Comment by bocklund** [comment]
This was closed by #52
