### ISSUE TITLE
The latest version of espei = 0.7.2 get an error when plot

### ISSUE THREAD

**Issue by duxiaoxian** [PhasesResearchLab/ESPEI#106]
I have recently used the latest version of espei = 0.7.2 and I always get an error, but I used espei = 0.6 and it works fine. 
![image](https://user-images.githubusercontent.com/45069457/60482502-5f6cce00-9cc4-11e9-8704-006106c09aaf.png)

My current computer can't use espei = 0.6 again, so I don't know which version to use, I don't know what went wrong. I always get MPI errors when I use espei = 0.6
![image](https://user-images.githubusercontent.com/45069457/60482527-6f84ad80-9cc4-11e9-9c14-0eb53727cb5a.png)

[AG_CU_1214.zip](https://github.com/PhasesResearchLab/ESPEI/files/3348278/AG_CU_1214.zip)

**Comment by bocklund** [comment]
What's the output of `conda list`?

**Comment by duxiaoxian** [comment]
[list.txt](https://github.com/PhasesResearchLab/ESPEI/files/3357484/list.txt)

**Comment by bocklund** [comment]
Can you share the script you are running and any relevant input files for your `plotin.py`?

**Comment by duxiaoxian** [comment]
All scripts and the input files are in the zip file in the previous dialog. Thank you very much.

**Comment by bocklund** [comment]
Ok @duxiaoxian, I was able to reproduce and understand your issue now.

The problem the unary Gibbs energy functions are defined as Piecewise functions in temperature, e.g.

```
FUNCTION GHSERAG 298.15 -3.98587E-7*T**3 - 0.001790585*T**2 -
   23.8463314*T*LN(T) + 118.202013*T - 7209.512 - 12011*T**(-1); 1234.93 Y
   -33.472*T*LN(T) + 190.266404*T - 15095.252 + 1.411773E+29*T**(-9); 3000.0
   N !```

defineds the Gibbs energy as that expression between 298.15 and 3000 K, and the GIbbs energy is 0 everywhere else (T<298.15 K or T>3000 K). In your calculations, the temperatures went below 298.15 K and all the phases have the same energy (0 J/mol), leading to the solver finding too many phases in equilibrium.

The fixes are either

1. Change your conditions to perform calculations within the bounds of the defined Gibbs energy expressions, or
2. Change the limits of the Piecewise expressions for the unary Gibbs energies and lattice stabilities to include the range you are interested in (for example, all of ESPEI's generated parameters are defined from 1 K to 10,000 K). Be aware that the SGTE unary expressions and lattice stabilities might not be accurate outside of these temperature ranges, particularly towards 0 K. Improving the unary descriptions to extend to 0 K is an active research area.

**Comment by duxiaoxian** [comment]
@bocklund When I set the minimum temperature at 300K, the problem was solved. Thank you very much for your help. This issue can be closed.
