### ISSUE TITLE
Espei not compatible with pycalphad 0.9.1  

### ISSUE THREAD

**Issue by wahab2604** [PhasesResearchLab/ESPEI#207]
When I do a fresh install of espei (via pip) it also installs pycalphad 0.9.1 and I get an Import Error:

" cannot import name 'pointsolve' from 'pycalphad.core.eqsolver' "

However, when I downgrade it to pycalphad 0.9.0 everything works fine

**Comment by bocklund** [comment]
@wahab2604 thanks for reporting this issue. There are few internal API changes in pycalphad 0.9.1 that necessitate a new release for ESPEI. The master branch is currently compatible with 0.9.1, we just need to make a new release 😄

**Comment by bocklund** [comment]
@wahab2604 ESPEI 0.8.5 that is compatible with pycalphad 0.9.1 should be available now!

**Comment by wahab2604** [comment]
Thank you very much, I am getting an Index error only when using binplot, but espei is working fine so i'll open the issue on the pycalphad Github
