### ISSUE TITLE
MCMC Initialized chains should include initial point

### ISSUE THREAD

**Issue by toastedcrumpets** [PhasesResearchLab/ESPEI#243]
During the initialization of the chains for the MCMC optimizer, a Gaussian distribution about an initial point is taken.
https://github.com/PhasesResearchLab/ESPEI/blob/7c797191d4c3178fe4a22275bbaee9c2977786ad/espei/optimizers/opt_mcmc.py#L98

I would suggest including the initial point in that set of initial chains. If everything is set up correctly, this won't matter, but for cases where the standard deviation is too high while the initial guess is quite good, the current behavior will lead to a lot of bad starting points. Modifying the initial set to include the initial guess point should ensure that at least this state (or acceptable permutations of it) will survive the MCMC run. What do you think?

**Comment by bocklund** [comment]
Yes, thanks for making this an issue. It's actually a feature I've wanted to implement for awhile, but haven't had the time yet. Feel free to take a stab at it (or anyone else who comes across this issue). 

I thought Emcee had a feature to allow giving a 0th iteration or something like that. That could be a way to do it. At worst, modifying the first of the randomly generated chains to match the initial set of parameters should be viable and reproducible.
