### ISSUE TITLE
Approach for fitting or providing VA model parameters

### ISSUE THREAD

**Issue by bocklund** [PhasesResearchLab/ESPEI#89]
Currently VA-only endmembers of phases cannot be fit. I think this is because there are 0 moles (vacancies don't have mass) which is causing any energies to fit to be zero when we convert from the dataset units of `1/mol-atom` to `1/mol-formula`. 

We either need to be able to fit VA-only endmembers or have users be able to provide their own models (since the models are usually fixed, e.g. 0 or 30T, etc.). Being able to fit the pure-VA endmembers probably does not make sense until users can provide custom models to be fit.

**Comment by bocklund** [comment]
Therefore, providing models fits in with #82

**Comment by richardotis** [comment]
Perhaps the best move for now is to hard-code the VA-only description according to Pin-Wen Guan and Zi-Kui Liu, "A physical model of thermal vacancies within the CALPHAD approach," _Scripta Materialia_, Volume 133, 2017.

**Comment by bocklund** [comment]
#102 allows for passing TDBs with fixed parameters, so this can be closed.
