### ISSUE TITLE
Tracing memory leaks in long-running jobs

### ISSUE THREAD

**Issue by richardotis** [PhasesResearchLab/ESPEI#9]
Note that this is a sketch of a procedure and contains code that has not yet been tested.

Key tools:
- `pympler` - find which objects are using the most memory
- `objgraph` - generate flow graphs of backreferences to any object
- `pyrasite` - attach a Python console to a running process

This will require some modification to the base code. Use the `SummaryTracker` from `pympler`. Add this code somewhere before MCMC sampling starts:
```python
from pympler import tracker
tr = tracker.SummaryTracker()
# Calibrate it by calling this a few times until it returns no changed objects
tr.print_diff()
tr.print_diff()
tr.print_diff()
# Create all the objects, put all the function's setup code
# All the sampling code is here
```
Start the sampling job with just a single core. Then use `pyrasite-shell` to connect to the running Python process by PID: http://pyrasite.readthedocs.io/en/latest/Shell.html

In the remote shell:
```python
import objgraph ; tr = objgraph.by_type('SummaryTracker')[0] ; tr.print_diff()
```
This will give output like:
```
                                     types |   # objects |   total size
========================================== | =========== | ============                                                                                      
                              <class 'list |       18730 |      1.71 MB                                                                                      
                               <class 'str |       18961 |      1.35 MB                                                                                      
              <class 'sip.methoddescriptor |        8287 |    453.20 KB                                                                                      
                              <class 'dict |         513 |    304.12 KB                                                                                      
                               <class 'int |        5375 |    152.21 KB                                                                                      
  <class 'sympy.core.assumptions.StdFactKB |         144 |     90.94 KB                                                                                      
                               <class 'set |          43 |     72.91 KB                                                                                      
                 <class '_lrucache.hashseq |         509 |     57.82 KB                                                                                      
                             <class 'tuple |         473 |     29.11 KB                                                                                      
          <class 'sympy.core.numbers.Float |         338 |     26.41 KB                                                                                      
                   <class '_lrucache.clist |         509 |     23.86 KB                                                                                      
           <class 'tinydb.database.Element |          32 |     15.50 KB
            <class 'sip.variabledescriptor |         184 |     12.94 KB
      <class 'PyQt4.QtCore.QLocale.Country |         248 |     12.59 KB
                <class 'sympy.core.mul.Mul |         174 |     12.23 KB
```
To start spot checking object backreferences, use
```python
objgraph.show_backrefs(objgraph.by_type('list')[0], max_depth=10)
```
A graph will be rendered as a PNG and written to a temporary directory. The path to the graph will be output to the console.

**Comment by richardotis** [comment]
A few potential culprits based on my testing on pycalphad by itself:
- pycalphad's cache: can be cleared with `pycalphad.core.cache.cacheit.cache_clear()`
- sympy's cache: can be cleared with `sympy.core.cache.clear_cache()`
- tinyDB's query cache: can be cleared with `db._query_cache.clear()`

The last one is interesting because it can cause the lifetime of a `Model`/`CompiledModel` object to be tied to the lifetime of a `Database` object; member functions of `Model`/`CompiledModel` will be entered into the query cache of the TinyDB in `Database`. Clearing the query cache fixed the problem in limited testing.

**Comment by bocklund** [comment]
Actions to take:

1. Implement the sketch in the original comment to get a baseline for where memory is being allocated over the course of a full run
2. Add the comment about sources of leaks in the developer docs? Or otherwise mark this because it's a good starting point for memory leaks for future devs.

**Comment by bocklund** [comment]
Memory stability seems good now since the release of pycalphad 0.6 close a leak of Database objects. Closing this.
