### ISSUE TITLE
Fitting to data that does not have certain model contributions

### ISSUE THREAD

**Issue by bocklund** [PhasesResearchLab/ESPEI#90]
Some data does not capture certain model contributions, particularly when that data is from simulations. As an example: experimental thermochemical data obviously captures all energy contributions, however DFT data can never capture the energy contributions that are modeled using the common CALPHAD magnetic models. We need to develop an approach that can signal that certain type of data should be fit (in parameter selection and in MCMC fitting) with/without certain model contributions.

Some considerations:

1. Since ESPEI will be used for custom model development, it would be ideal for model contribution information to *not* be embedded in the data so that the datasets are still transferable.
2. How to specify the contributions such as inclusive: *"My data should be fit considering only these model contributions"*, or exclusive: *"My data should be fit to all model contributions except these"* or both.

**Comment by richardotis** [comment]
Related to this, I've received an inquiry about the ability to also handle metastable phase equilibria, so that the data can control which phases are entered in the calculation.
